### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by Chilliann** [TechsCode/UltraPermissionsDatabase#17]
I currently have a problem with permissions resetting on a server reset using /stop and starting it up.
I added the permission plots.use in the world plots and when i did a reset the permission was still there but unable to use the commands for plots. Also noticed it with adding the minecraft op/deop permission to my Owner group, it worked until i did a reset. The permission stays in the GUI menu but unable to use the command.

Currently on v4.1.6 - Spigot 1.13.2

**Comment by Chilliann** [comment]
Updated to the latest 4.1.9 and at the end of my console start up i got this.


[16:18:17 WARN]: [UltraPermissions] Plugin UltraPermissions v4.1.9 generated an exception while executing task 1875
java.lang.IllegalStateException: Not a JSON Object: null
        at me.TechsCode.UltraPermissions.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[?:?]
        at me.TechsCode.UltraPermissions.tpl.SkinTexture.fromMojangAPI(SkinTexture.java:32) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader.lambda$update$2(HeadPreloader.java:55) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader$$Lambda$2288/96298003.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_40]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[16:19:19 WARN]: [UltraPermissions] Plugin UltraPermissions v4.1.9 generated an exception while executing task 3007
java.lang.IllegalStateException: Not a JSON Object: null
        at me.TechsCode.UltraPermissions.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[?:?]
        at me.TechsCode.UltraPermissions.tpl.SkinTexture.fromMojangAPI(SkinTexture.java:32) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader.lambda$update$2(HeadPreloader.java:55) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader$$Lambda$2288/96298003.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_40]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[16:20:18 WARN]: [UltraPermissions] Plugin UltraPermissions v4.1.9 generated an exception while executing task 4139
java.lang.IllegalStateException: Not a JSON Object: null
        at me.TechsCode.UltraPermissions.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[?:?]
        at me.TechsCode.UltraPermissions.tpl.SkinTexture.fromMojangAPI(SkinTexture.java:32) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader.lambda$update$2(HeadPreloader.java:55) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader$$Lambda$2288/96298003.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_40]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[16:21:19 WARN]: [UltraPermissions] Plugin UltraPermissions v4.1.9 generated an exception while executing task 5270
java.lang.IllegalStateException: Not a JSON Object: null
        at me.TechsCode.UltraPermissions.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[?:?]
        at me.TechsCode.UltraPermissions.tpl.SkinTexture.fromMojangAPI(SkinTexture.java:32) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader.lambda$update$2(HeadPreloader.java:55) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader$$Lambda$2288/96298003.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_40]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[16:22:18 WARN]: [UltraPermissions] Plugin UltraPermissions v4.1.9 generated an exception while executing task 6403
java.lang.IllegalStateException: Not a JSON Object: null
        at me.TechsCode.UltraPermissions.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[?:?]
        at me.TechsCode.UltraPermissions.tpl.SkinTexture.fromMojangAPI(SkinTexture.java:32) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader.lambda$update$2(HeadPreloader.java:55) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader$$Lambda$2288/96298003.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_40]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[16:23:19 WARN]: [UltraPermissions] Plugin UltraPermissions v4.1.9 generated an exception while executing task 7535
java.lang.IllegalStateException: Not a JSON Object: null
        at me.TechsCode.UltraPermissions.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[?:?]
        at me.TechsCode.UltraPermissions.tpl.SkinTexture.fromMojangAPI(SkinTexture.java:32) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader.lambda$update$2(HeadPreloader.java:55) ~[?:?]
        at me.TechsCode.UltraPermissions.HeadPreloader$$Lambda$2288/96298003.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_40]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
>

**Comment by tedztar** [comment]
Hey please go to techs support discord here: https://discordapp.com/invite/aApqC64

**Comment by DAmNRelentless** [comment]
See the answer above. You can report bugs and get help on the Discord.
